name: Build and Upload APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Expo & EAS
        run: |
          npm install -g expo-cli eas-cli

      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx expo whoami || npx expo login --token $EXPO_TOKEN

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Android APK
        working-directory: ./client
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production --non-interactive --wait

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: talkochat-apk
          path: ./client/build/*.apk
